# Generated by Django 2.2.2 on 2019-06-19 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('riders', '0002_route_car'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='route',
            options={'ordering': ['departureTime']},
        ),
        migrations.AddField(
            model_name='route',
            name='imgURL',
            field=models.CharField(default='https://maps.googleapis.com/maps/api/staticmap?size=300x200&key=AIzaSyDMRscPhFN-k1XKwTwrAnSSdAv7KbbRCcI&markers=San Francisco', max_length=300),
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riders.Profile')),
            ],
        ),
    ]
