# Generated by Django 2.2.2 on 2019-06-19 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riders', '0003_auto_20190618_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='imgURL',
            field=models.CharField(default='https://maps.googleapis.com/maps/api/staticmap?size=300x200&key=AIzaSyDMRscPhFN-k1XKwTwrAnSSdAv7KbbRCcI&markers=San Francisco', max_length=1000),
        ),
    ]
